### ISSUE TITLE
Usage of this repo in github/linguist

### ISSUE THREAD

**Issue by Epokhe** [Jason3S/avro.tmLanguage#2]
FYI @Jason3S

I used the avdl grammar in this repo in order to provide syntax highlighting to avdl files on Github.

PR here: https://github.com/github/linguist/pull/4953

It will take a while until the changes are released.

**Comment by Epokhe** [comment]
(You can close the issue, it was just to inform you)

**Comment by Jason3S** [comment]
Cool! Thank you. I get a bit busy sometimes and do not see all the message.

**Comment by Jason3S** [comment]
@Epokhe,

I'm not sure if you still use this, but I have updated it to handle functions and back ticks `` ` ``.

**Comment by Epokhe** [comment]
Thanks @Jason3S. Yes, Github linguist refers to your repo as a submodule as you can see here: https://github.com/github/linguist/tree/master/vendor/grammars

And I've seen that [grammar submodules are updated automatically with each new release](https://github.com/github/linguist/issues/4170#issuecomment-399210062).

When they make a release, your change should go live, and backticks here should get colorized(that's my assumption because you said backticks):
https://github.com/Jason3S/avro.tmLanguage/blob/a4bff4beac8a745e1836f8d8aa57966c4f0e222f/samples/avdl/example1.10.2.avdl#L39

**Comment by Epokhe** [comment]
@Jason3S Linguist [just made a release](https://github.com/github/linguist/pull/5489) and you can see that the lines with backticks are colorized

**Comment by Jason3S** [comment]
@Epokhe Thank you.
